-- Brands being tracked
CREATE TABLE IF NOT EXISTS brands (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  peec_project_id TEXT NOT NULL,
  competitors TEXT[] DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Visibility snapshots pulled from Peec AI
CREATE TABLE IF NOT EXISTS visibility_snapshots (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  brand_id UUID REFERENCES brands(id) ON DELETE CASCADE,
  snapshot_date DATE DEFAULT CURRENT_DATE,
  overall_score NUMERIC(5,2),
  competitor_scores JSONB DEFAULT '{}',
  gap_topics JSONB DEFAULT '[]',
  raw_response JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Sources found by Tavily where competitors win
CREATE TABLE IF NOT EXISTS competitor_sources (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  brand_id UUID REFERENCES brands(id) ON DELETE CASCADE,
  snapshot_id UUID REFERENCES visibility_snapshots(id),
  source_url TEXT NOT NULL,
  source_type TEXT,
  competitor_name TEXT,
  topic TEXT,
  tavily_score NUMERIC(4,3),
  content_snippet TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Content drafts generated by Claude
CREATE TABLE IF NOT EXISTS content_drafts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  brand_id UUID REFERENCES brands(id) ON DELETE CASCADE,
  source_id UUID REFERENCES competitor_sources(id),
  content_type TEXT NOT NULL,
  title TEXT,
  body TEXT NOT NULL,
  target_url TEXT,
  status TEXT DEFAULT 'pending',
  entire_task_id TEXT,
  approved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Actions log: what ran, what changed in Peec after
CREATE TABLE IF NOT EXISTS action_results (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  brand_id UUID REFERENCES brands(id) ON DELETE CASCADE,
  draft_id UUID REFERENCES content_drafts(id),
  score_before NUMERIC(5,2),
  score_after NUMERIC(5,2),
  delta NUMERIC(5,2),
  measured_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed demo brand (Nothing Phone)
INSERT INTO brands (name, slug, peec_project_id, competitors)
VALUES (
  'Nothing Phone',
  'nothing-phone',
  'demo-nothing-phone',
  ARRAY['Apple', 'Samsung']
)
ON CONFLICT (slug) DO NOTHING;

-- Seed demo brands (Attio, BYD)
INSERT INTO brands (name, slug, peec_project_id, competitors)
VALUES (
  'Attio',
  'attio',
  'demo-attio',
  ARRAY['Salesforce', 'HubSpot']
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO brands (name, slug, peec_project_id, competitors)
VALUES (
  'BYD',
  'byd',
  'demo-byd',
  ARRAY['Tesla']
)
ON CONFLICT (slug) DO NOTHING;
